import type { ModuleEntry } from "./types";

export const CORRIDORS: ModuleEntry[] = [
  {
    key: "instc",
    faTitle: "کریدور شمال–جنوب (INSTC)",
    enTitle: "INSTC North-South Corridor",
    value: "اتصال خلیج فارس به قفقاز، روسیه و اوراسیا روی کریدور شمال–جنوب.",
    pain: "ترانزیت روی کریدور شمال–جنوب چندمرحله‌ای و بدون دید یکپارچه است.",
    solution: "iKIA بار، اسناد و گذرگاه‌های کریدور شمال–جنوب را یکپارچه می‌کند.",
    status: "strategic-future",
    targetUsers: ["بازرگانان", "فورواردرها", "نهادهای حاکمیتی"],
    route: "/corridors/instc",
    icon: "corridor",
    cta: "گفتگو درباره کریدور",
    category: "corridor",
    detail: {
      pains: [
        { title: "چندمرحله‌ای بودن", desc: "ترکیب جاده، ریل و دریا در کریدور پیچیده است." },
        { title: "گلوگاه مرز", desc: "گذر از مرزها زمان‌بر و کاغذی است." },
        { title: "نبود دید سرتاسری", desc: "وضعیت بار در کل کریدور دیده نمی‌شود." },
      ],
      capabilities: [
        { icon: "corridor", title: "مدیریت کریدور", desc: "بار روی کریدور شمال–جنوب." },
        { icon: "multimodal", title: "اتصال چندوجهی", desc: "ترکیب جاده، ریل و دریا." },
        { icon: "customs", title: "گذرگاه مرزی", desc: "هماهنگی مرز و گمرک." },
        { icon: "tracking", title: "رهگیری کریدوری", desc: "دید سرتاسری از مبدأ تا مقصد." },
      ],
      steps: [
        { title: "طراحی مسیر", desc: "ترکیب کریدوری انتخاب می‌شود." },
        { title: "هماهنگی", desc: "اتصال‌ها و مرزها برنامه‌ریزی می‌شوند." },
        { title: "ترانزیت", desc: "بار روی کریدور حرکت و رهگیری می‌شود." },
        { title: "تحویل", desc: "تحویل و تسویه نهایی." },
      ],
      controls: [
        { title: "انطباق ترانزیت", desc: "سوابق گذر مرزی." },
        { title: "هماهنگی نهادها", desc: "اتصال داده به نهادهای مرتبط." },
        { title: "گزارش کریدور", desc: "شاخص‌های عملکرد کریدوری." },
      ],
    },
  },
  {
    key: "east-west",
    faTitle: "کریدور شرق–غرب",
    enTitle: "East-West / New Silk Road",
    value: "مسیر ترانزیت شرق به غرب میان آسیا و اروپا از خاک ایران.",
    pain: "مسیر شرق–غرب پتانسیل بالایی دارد اما هماهنگی آن پیچیده است.",
    solution: "iKIA بار و اسناد کریدور شرق–غرب را در یک جریان مدیریت می‌کند.",
    status: "strategic-future",
    targetUsers: ["بازرگانان", "فورواردرها", "صنایع"],
    route: "/corridors/east-west",
    icon: "corridor",
    cta: "گفتگو درباره کریدور",
    category: "corridor",
    detail: {
      pains: [
        { title: "هماهنگی فرامرزی", desc: "اتصال چند کشور و گمرک پیچیده است." },
        { title: "نبود استاندارد", desc: "اسناد و فرایندها یکدست نیستند." },
        { title: "دید محدود", desc: "وضعیت ترانزیت شفاف نیست." },
      ],
      capabilities: [
        { icon: "corridor", title: "مدیریت ترانزیت", desc: "بار روی کریدور شرق–غرب." },
        { icon: "documents", title: "اسناد ترانزیت", desc: "مدارک فرامرزی یکپارچه." },
        { icon: "customs", title: "گذرگاه‌ها", desc: "هماهنگی مرز و گمرک." },
        { icon: "tracking", title: "رهگیری مسیر", desc: "دید کامل ترانزیت." },
      ],
      steps: [
        { title: "برنامه‌ریزی", desc: "مسیر و گذرگاه‌ها مشخص می‌شوند." },
        { title: "هماهنگی", desc: "اسناد و مرزها آماده می‌شوند." },
        { title: "ترانزیت", desc: "بار حرکت و رهگیری می‌شود." },
        { title: "تحویل", desc: "تحویل و تسویه نهایی." },
      ],
      controls: [
        { title: "انطباق فرامرزی", desc: "سوابق ترانزیت قابل ممیزی." },
        { title: "هماهنگی شرکا", desc: "اتصال به شرکای مسیر." },
        { title: "گزارش", desc: "شاخص‌های کریدور." },
      ],
    },
  },
  {
    key: "domestic",
    faTitle: "مسیرهای راهبردی داخلی",
    enTitle: "Domestic Strategic Routes",
    value: "کریدورهای پرتردد داخلی به‌عنوان پایه شبکه حمل.",
    pain: "مسیرهای داخلی ظرفیت بالایی دارند اما بهینه استفاده نمی‌شوند.",
    solution: "iKIA مسیرهای داخلی را به شبکه بار و ظرفیت وصل می‌کند.",
    status: "current",
    targetUsers: ["صاحبان بار", "کریرها"],
    route: "/corridors",
    icon: "route",
    cta: "مشاهده کریدورها",
    category: "corridor",
  },
  {
    key: "border-gateways",
    faTitle: "درگاه‌های مرزی و گمرکی",
    enTitle: "Border & Customs Gateways",
    value: "مدیریت گذرگاه‌های مرزی و گمرکی به‌صورت یکپارچه.",
    pain: "گذرگاه‌های مرزی گلوگاه اصلی ترانزیت‌اند.",
    solution: "iKIA هماهنگی مرز و گمرک را به جریان حمل وصل می‌کند.",
    status: "near-future",
    targetUsers: ["فورواردرها", "بازرگانان", "نهادها"],
    route: "/corridors",
    icon: "customs",
    cta: "مشاهده کریدورها",
    category: "corridor",
  },
  {
    key: "hub-network",
    faTitle: "شبکه ۵۸ مرکز لجستیک",
    enTitle: "58 Logistics Hubs Network",
    value: "شبکه‌ای از مراکز لجستیک به‌عنوان ستون فقرات حمل کشور.",
    pain: "مراکز لجستیک پراکنده‌اند و به‌صورت شبکه دیده نمی‌شوند.",
    solution: "iKIA مراکز لجستیک را به یک شبکه زنده و متصل تبدیل می‌کند.",
    status: "strategic-future",
    targetUsers: ["مراکز لجستیک", "نهادها", "سازمان‌ها"],
    route: "/corridors",
    icon: "hub",
    cta: "مشاهده کریدورها",
    category: "corridor",
  },
];
