import type { ModuleEntry } from "./types";

export const PLATFORM: ModuleEntry[] = [
  {
    key: "control-tower",
    faTitle: "برج کنترل",
    enTitle: "Control Tower",
    value: "دید لحظه‌ای روی سفارش‌ها، ناوگان، وضعیت مسیر و رخدادهای عملیاتی.",
    pain: "تصمیم‌گیری بدون دید یکپارچه از عملیات، کند و پرریسک است.",
    solution: "برج کنترل iKIA همه‌چیز را در یک نمای زنده برای دیدن، تصمیم و اقدام جمع می‌کند.",
    status: "near-future",
    targetUsers: ["مدیران عملیات", "فورواردرها", "سازمان‌ها"],
    route: "/platform/control-tower",
    icon: "control-tower",
    cta: "مشاهده برج کنترل",
    category: "platform",
    detail: {
      pains: [
        { title: "داده پراکنده", desc: "اطلاعات عملیات در سامانه‌های جدا پخش است." },
        { title: "واکنش کند", desc: "رخدادها دیر دیده و دیرتر مدیریت می‌شوند." },
        { title: "نبود اولویت", desc: "مهم‌ترین استثناها گم می‌شوند." },
      ],
      capabilities: [
        { icon: "control-tower", title: "نمای زنده", desc: "وضعیت همه محموله‌ها در یک داشبورد." },
        { icon: "bell", title: "استثناها و هشدار", desc: "رخدادهای مهم برجسته می‌شوند." },
        { icon: "route", title: "وضعیت مسیر", desc: "پیشرفت هر سفر روی مسیر و کریدور." },
        { icon: "analytics", title: "شاخص عملیاتی", desc: "تأخیر، تطبیق ظرفیت و زمان تحویل." },
      ],
      steps: [
        { title: "اتصال داده", desc: "سفارش، ناوگان و اسناد یک‌جا می‌آیند." },
        { title: "پایش", desc: "وضعیت زنده عملیات دیده می‌شود." },
        { title: "تصمیم", desc: "استثناها اولویت‌بندی و مدیریت می‌شوند." },
        { title: "اقدام", desc: "اقدام در لحظه روی همان نما." },
      ],
      controls: [
        { title: "دسترسی نقش‌محور", desc: "هر نقش نمای مجاز خود را می‌بیند." },
        { title: "سوابق رویداد", desc: "هر تغییر ثبت و قابل ممیزی است." },
        { title: "هشدار آستانه", desc: "هشدار خودکار برای تأخیر و ریسک." },
      ],
    },
  },
  {
    key: "visibility",
    faTitle: "رهگیری لحظه‌ای",
    enTitle: "Real-Time Visibility",
    value: "موقعیت و وضعیت زنده محموله از مبدأ تا مقصد.",
    pain: "نبود رهگیری شفاف، اعتماد و برنامه‌ریزی را سخت می‌کند.",
    solution: "iKIA وضعیت و موقعیت محموله را به‌صورت زنده و قابل اتکا نشان می‌دهد.",
    status: "near-future",
    targetUsers: ["صاحبان بار", "فورواردرها"],
    route: "/platform/visibility",
    icon: "tracking",
    cta: "مشاهده رهگیری",
    category: "platform",
    detail: {
      pains: [
        { title: "بی‌خبری از وضعیت", desc: "تا تحویل، خبری از بار نیست." },
        { title: "تماس‌های پیاپی", desc: "پیگیری دستی، زمان‌بر و ناقص است." },
        { title: "نبود ETA", desc: "زمان تحویل قابل اتکا نیست." },
      ],
      capabilities: [
        { icon: "map", title: "نمای زنده", desc: "موقعیت و وضعیت روی نقشه." },
        { icon: "mobile", title: "موبایل راننده", desc: "دریافت موقعیت از اپ کریر." },
        { icon: "bell", title: "رویداد و وضعیت", desc: "ثبت تغییرات برای شفافیت." },
        { icon: "navigation", title: "آماده GPS", desc: "معماری آماده داده موقعیت." },
      ],
      steps: [
        { title: "شروع سفر", desc: "محموله وارد چرخه رهگیری می‌شود." },
        { title: "به‌روزرسانی", desc: "موقعیت و وضعیت زنده می‌شود." },
        { title: "ETA", desc: "زمان تحویل تخمین زده می‌شود." },
        { title: "تحویل", desc: "تحویل ثبت و چرخه بسته می‌شود." },
      ],
      controls: [
        { title: "صحت داده", desc: "اعتبارسنجی رویدادهای موقعیت." },
        { title: "حریم دسترسی", desc: "اشتراک وضعیت فقط با طرف‌های مجاز." },
        { title: "سوابق سفر", desc: "تاریخچه کامل برای انطباق." },
      ],
    },
  },
  {
    key: "order-management",
    faTitle: "مدیریت سفارش",
    enTitle: "Order Management",
    value: "چرخه عمر سفارش از ثبت تا تخصیص، حمل، تحویل و تسویه.",
    pain: "سفارش‌ها در ابزارهای پراکنده مدیریت می‌شوند و گم می‌شوند.",
    solution: "iKIA چرخه عمر سفارش را در یک جریان منسجم مدیریت می‌کند.",
    status: "current",
    targetUsers: ["صاحبان بار", "فورواردرها"],
    route: "/platform/order-management",
    icon: "order",
    cta: "مشاهده مدیریت سفارش",
    category: "platform",
    detail: {
      pains: [
        { title: "پراکندگی ابزار", desc: "سفارش‌ها در فایل و پیام مدیریت می‌شوند." },
        { title: "نبود وضعیت", desc: "مرحله هر سفارش روشن نیست." },
        { title: "خطای دستی", desc: "هماهنگی دستی، خطاپذیر است." },
      ],
      capabilities: [
        { icon: "register", title: "ثبت سفارش", desc: "ایجاد سریع سفارش و الزامات." },
        { icon: "lifecycle", title: "چرخه عمر", desc: "وضعیت هر سفارش از ثبت تا تسویه." },
        { icon: "assign", title: "تخصیص", desc: "واگذاری به فورواردر/کریر." },
        { icon: "workflow", title: "اتوماسیون", desc: "مراحل عملیاتی خودکار." },
      ],
      steps: [
        { title: "ثبت", desc: "سفارش ایجاد می‌شود." },
        { title: "تخصیص", desc: "بار به ظرفیت مناسب می‌رسد." },
        { title: "اجرا", desc: "حمل و وضعیت پیگیری می‌شود." },
        { title: "تسویه", desc: "تحویل و آماده‌سازی تسویه." },
      ],
      controls: [
        { title: "سوابق سفارش", desc: "تاریخچه کامل هر سفارش." },
        { title: "دسترسی کنترل‌شده", desc: "مشاهده بر اساس نقش." },
        { title: "قواعد عملیاتی", desc: "اعمال قواعد در مراحل کار." },
      ],
    },
  },
  {
    key: "documents-compliance",
    faTitle: "اسناد و انطباق",
    enTitle: "Documents & Compliance",
    value: "مدیریت بارنامه، بیمه، گواهی، اظهارنامه و کنترل تطبیق.",
    pain: "اسناد حمل پراکنده‌اند و انطباق مقرراتی دستی و پرریسک است.",
    solution: "iKIA اسناد را منظم و سوابق انطباق را قابل ممیزی نگه می‌دارد.",
    status: "near-future",
    targetUsers: ["همه نقش‌ها", "بازرگانان"],
    route: "/platform/documents-compliance",
    icon: "documents",
    cta: "مشاهده اسناد و انطباق",
    category: "platform",
    detail: {
      pains: [
        { title: "اسناد پراکنده", desc: "مدارک در ایمیل و کاغذ گم می‌شوند." },
        { title: "ریسک انطباق", desc: "نبود سوابق، ممیزی را سخت می‌کند." },
        { title: "تطبیق دستی", desc: "کنترل مدارک زمان‌بر و خطاپذیر است." },
      ],
      capabilities: [
        { icon: "documents", title: "مدیریت اسناد", desc: "بارنامه، بیمه و گواهی‌ها در یک‌جا." },
        { icon: "customs", title: "اظهار و گمرک", desc: "هماهنگی مدارک گمرکی." },
        { icon: "compliance", title: "کنترل تطبیق", desc: "چارچوب رعایت الزامات." },
        { icon: "audit", title: "سوابق ممیزی", desc: "ردگیری کامل برای حسابرسی." },
      ],
      steps: [
        { title: "بارگذاری", desc: "مدارک هر محموله ثبت می‌شوند." },
        { title: "تطبیق", desc: "اسناد با الزامات کنترل می‌شوند." },
        { title: "تأیید", desc: "وضعیت تطبیق روشن می‌شود." },
        { title: "بایگانی", desc: "سوابق برای ممیزی نگه‌داری می‌شود." },
      ],
      controls: [
        { title: "دسترسی امن", desc: "مشاهده اسناد بر اساس نقش." },
        { title: "نسخه و تاریخچه", desc: "ثبت تغییرات مدارک." },
        { title: "آماده ممیزی", desc: "خروجی سوابق برای حسابرسی." },
      ],
    },
  },
  {
    key: "integrations",
    faTitle: "API و یکپارچه‌سازی",
    enTitle: "API / Partner Integrations",
    value: "اتصال سامانه‌ها و شرکا به جریان عملیات iKIA.",
    pain: "داده عملیات در سامانه‌های جدا حبس می‌شود و یکپارچه نیست.",
    solution: "iKIA با API و یکپارچه‌سازی، سامانه‌ها و شرکا را به هم وصل می‌کند.",
    status: "strategic-future",
    targetUsers: ["توسعه‌دهندگان", "سازمان‌ها", "شرکا"],
    route: "/platform/integrations",
    icon: "api",
    cta: "مشاهده یکپارچه‌سازی",
    category: "platform",
    detail: {
      pains: [
        { title: "داده جزیره‌ای", desc: "هر سامانه جدا و بدون اتصال است." },
        { title: "ورود دستی", desc: "انتقال داده دستی، کند و خطاپذیر است." },
        { title: "نبود استاندارد", desc: "اتصال شرکا بدون چارچوب سخت است." },
      ],
      capabilities: [
        { icon: "api", title: "APIهای iKIA", desc: "دسترسی برنامه‌نویسی به جریان عملیات." },
        { icon: "developers", title: "ابزار توسعه", desc: "مستندات و ابزار اتصال." },
        { icon: "workflow", title: "رویداد و وب‌هوک", desc: "اطلاع‌رسانی رویدادها به سامانه‌ها." },
        { icon: "lock", title: "امنیت دسترسی", desc: "کلید و دسترسی کنترل‌شده." },
      ],
      steps: [
        { title: "دسترسی", desc: "کلید API و محیط آزمایش." },
        { title: "اتصال", desc: "سامانه شما به iKIA وصل می‌شود." },
        { title: "همگام‌سازی", desc: "داده و رویدادها رد و بدل می‌شوند." },
        { title: "عملیات", desc: "جریان یکپارچه در محیط واقعی." },
      ],
      controls: [
        { title: "کنترل دسترسی", desc: "مجوزهای دقیق برای هر اتصال." },
        { title: "پایش مصرف", desc: "نظارت بر استفاده از API." },
        { title: "سوابق فراخوان", desc: "ثبت رویدادهای اتصال." },
      ],
    },
  },
  // Modules surfaced on the homepage/menu but routed to the platform overview
  // until they get dedicated pages.
  {
    key: "booking",
    faTitle: "رزرو و ظرفیت",
    enTitle: "Booking / Capacity",
    value: "رزرو ظرفیت حمل به‌صورت شفاف و سریع.",
    pain: "یافتن و رزرو ظرفیت مطمئن دشوار است.",
    solution: "iKIA رزرو ظرفیت را ساده و قابل اتکا می‌کند.",
    status: "current",
    targetUsers: ["صاحبان بار", "کریرها"],
    route: "/platform",
    icon: "booking",
    cta: "مشاهده پلتفرم",
    category: "platform",
  },
  {
    key: "smart-matching",
    faTitle: "تخصیص هوشمند",
    enTitle: "Smart Matching",
    value: "اتصال بار به مناسب‌ترین ظرفیت بر اساس مسیر، قیمت و قابلیت اتکا.",
    pain: "تطبیق دستی بار و ظرفیت، کند و غیربهینه است.",
    solution: "موتور تطبیق iKIA بهترین ظرفیت را پیشنهاد می‌دهد.",
    status: "near-future",
    targetUsers: ["صاحبان بار", "کریرها", "فورواردرها"],
    route: "/platform",
    icon: "matching",
    cta: "مشاهده پلتفرم",
    category: "platform",
  },
  {
    key: "dynamic-pricing",
    faTitle: "قیمت‌گذاری پویا",
    enTitle: "Dynamic Pricing",
    value: "نرخ شفاف و پویا بر اساس مسیر، تقاضا و شرایط.",
    pain: "قیمت‌گذاری مبهم، تصمیم را سخت می‌کند.",
    solution: "iKIA قیمت را شفاف و قابل مقایسه می‌کند.",
    status: "near-future",
    targetUsers: ["صاحبان بار", "فورواردرها"],
    route: "/platform",
    icon: "price",
    cta: "مشاهده پلتفرم",
    category: "platform",
  },
  {
    key: "workflow-engine",
    faTitle: "موتور فرایند",
    enTitle: "Workflow Engine",
    value: "اتوماسیون مراحل عملیاتی و قواعد کسب‌وکار.",
    pain: "مراحل دستی، کند و ناهماهنگ است.",
    solution: "موتور فرایند iKIA مراحل را خودکار و منسجم می‌کند.",
    status: "near-future",
    targetUsers: ["اپراتورها", "سازمان‌ها"],
    route: "/platform",
    icon: "workflow",
    cta: "مشاهده پلتفرم",
    category: "platform",
  },
  {
    key: "notifications",
    faTitle: "اعلان‌ها",
    enTitle: "Notifications",
    value: "اطلاع‌رسانی به‌موقع رویدادهای عملیاتی.",
    pain: "رویدادهای مهم دیر به اطلاع می‌رسند.",
    solution: "iKIA رویدادها را به‌موقع اطلاع می‌دهد.",
    status: "current",
    targetUsers: ["همه نقش‌ها"],
    route: "/platform",
    icon: "bell",
    cta: "مشاهده پلتفرم",
    category: "platform",
  },
  {
    key: "analytics",
    faTitle: "داده و گزارش",
    enTitle: "Analytics & Reporting",
    value: "گزارش و شاخص‌های عملیاتی برای تصمیم بهتر.",
    pain: "نبود گزارش یکپارچه، مدیریت را سخت می‌کند.",
    solution: "iKIA داده عملیات را به بینش تبدیل می‌کند.",
    status: "near-future",
    targetUsers: ["مدیران", "سازمان‌ها"],
    route: "/platform",
    icon: "analytics",
    cta: "مشاهده پلتفرم",
    category: "platform",
  },
];
