import type { ModuleEntry } from "./types";

export const SOLUTIONS: ModuleEntry[] = [
  {
    key: "shippers",
    faTitle: "صاحبان بار",
    enTitle: "Shippers / Cargo Owners",
    value: "ثبت بار، قیمت شفاف، انتخاب حمل‌کننده و رهگیری تا تحویل.",
    pain: "صاحبان بار با قیمت مبهم و نبود دید روبه‌رو هستند.",
    solution: "iKIA ثبت بار تا تحویل را شفاف و قابل کنترل می‌کند.",
    status: "current",
    targetUsers: ["صاحبان بار", "بازرگانان"],
    route: "/solutions/shippers",
    icon: "package",
    cta: "ثبت اولین بار",
    category: "solution",
    detail: {
      pains: [
        { title: "قیمت مبهم", desc: "نبود شفافیت قیمت تصمیم را سخت می‌کند." },
        { title: "واسطه‌های متعدد", desc: "زنجیره واسطه هزینه و زمان می‌افزاید." },
        { title: "بی‌خبری", desc: "وضعیت بار تا تحویل روشن نیست." },
      ],
      capabilities: [
        { icon: "register", title: "ثبت بار", desc: "ثبت سریع محموله و الزامات." },
        { icon: "price", title: "قیمت شفاف", desc: "مقایسه شفاف پیشنهادها." },
        { icon: "check", title: "انتخاب حمل‌کننده", desc: "انتخاب فورواردر یا کریر مناسب." },
        { icon: "tracking", title: "رهگیری", desc: "پیگیری تا تحویل نهایی." },
      ],
      steps: [
        { title: "ثبت بار", desc: "مشخصات بار را وارد کنید." },
        { title: "پیشنهاد", desc: "قیمت‌های شفاف را ببینید." },
        { title: "انتخاب", desc: "حمل‌کننده مناسب را برگزینید." },
        { title: "تحویل", desc: "وضعیت را تا تحویل دنبال کنید." },
      ],
      controls: [
        { title: "شفافیت", desc: "قیمت و وضعیت روشن." },
        { title: "سوابق", desc: "تاریخچه کامل هر بار." },
        { title: "کنترل دسترسی", desc: "داده شما نزد شما." },
      ],
    },
  },
  {
    key: "forwarders",
    faTitle: "فورواردرها",
    enTitle: "Freight Forwarders",
    value: "یافتن بار و ظرفیت، مدیریت چند محموله، پیشنهاددهی و اسناد.",
    pain: "فورواردرها بار را میان کانال‌های پراکنده مدیریت می‌کنند.",
    solution: "iKIA بار، ظرفیت، پیشنهاد و اسناد را در یک پنل جمع می‌کند.",
    status: "current",
    targetUsers: ["فورواردرها"],
    route: "/solutions/forwarders",
    icon: "boxes",
    cta: "شروع در پنل وب",
    category: "solution",
    detail: {
      pains: [
        { title: "پراکندگی بار", desc: "یافتن بار میان کانال‌ها زمان‌بر است." },
        { title: "چند محموله", desc: "مدیریت هم‌زمان بدون ابزار سخت است." },
        { title: "اسناد دستی", desc: "نگه‌داری مدارک خطاپذیر است." },
      ],
      capabilities: [
        { icon: "search", title: "یافتن بار و ظرفیت", desc: "دسترسی به بار و ظرفیت مسیر." },
        { icon: "lifecycle", title: "مدیریت چند محموله", desc: "اداره چند بار در یک نما." },
        { icon: "offer", title: "پیشنهاددهی", desc: "ثبت و پیگیری پیشنهادها." },
        { icon: "documents", title: "اسناد و پیگیری", desc: "مدارک و وضعیت بار." },
      ],
      steps: [
        { title: "یافتن بار", desc: "بار مسیر خود را بیابید." },
        { title: "پیشنهاد", desc: "قیمت و شرایط را ثبت کنید." },
        { title: "مدیریت", desc: "چند محموله را اداره کنید." },
        { title: "اسناد", desc: "تحویل و مدارک را ببندید." },
      ],
      controls: [
        { title: "نمای متمرکز", desc: "همه محموله‌ها یک‌جا." },
        { title: "سوابق", desc: "تاریخچه پیشنهاد و حمل." },
        { title: "دسترسی نقش‌محور", desc: "کنترل داده تیم." },
      ],
    },
  },
  {
    key: "carriers",
    faTitle: "کریرها و ناوگان",
    enTitle: "Carriers / Fleet / Drivers",
    value: "بارهای نزدیک، سفرهای جاری، مدیریت ناوگان و تسویه.",
    pain: "خالی‌برگشت و نبود دسترسی موبایل به بار، درآمد را کم می‌کند.",
    solution: "iKIA تجربه موبایل‌فرست برای بار نزدیک و تسویه فراهم می‌کند.",
    status: "current",
    targetUsers: ["کریرها", "ناوگان", "رانندگان"],
    route: "/solutions/carriers",
    icon: "truck",
    cta: "ورود کریر",
    category: "solution",
    detail: {
      pains: [
        { title: "خالی‌برگشت", desc: "بازگشت بدون بار درآمد را کم می‌کند." },
        { title: "دسترسی به بار", desc: "یافتن بار نزدیک بدون موبایل سخت است." },
        { title: "ابهام تسویه", desc: "شفافیت درآمد و تسویه کم است." },
      ],
      capabilities: [
        { icon: "mobile", title: "موبایل‌فرست", desc: "تجربه روی گوشی راننده." },
        { icon: "tracking", title: "بارهای نزدیک", desc: "بار در نزدیکی مسیر." },
        { icon: "fleet", title: "مدیریت ناوگان", desc: "سفرهای جاری و وضعیت ناوگان." },
        { icon: "finance", title: "درآمد و تسویه", desc: "پیگیری درآمد و آمادگی تسویه." },
      ],
      steps: [
        { title: "نصب اپ", desc: "نسخه موبایل کریر را نصب کنید." },
        { title: "بار نزدیک", desc: "بار مسیر خود را پیدا کنید." },
        { title: "سفر", desc: "سفر جاری را مدیریت کنید." },
        { title: "تسویه", desc: "درآمد و تسویه را دنبال کنید." },
      ],
      controls: [
        { title: "شفافیت درآمد", desc: "وضعیت مالی روشن." },
        { title: "سوابق سفر", desc: "تاریخچه سفرها." },
        { title: "کنترل ناوگان", desc: "مدیریت دسترسی رانندگان." },
      ],
    },
  },
  {
    key: "logistics-hubs",
    faTitle: "مراکز لجستیک",
    enTitle: "Logistics Hubs / Warehouses",
    value: "اتصال ظرفیت انبار و مراکز لجستیک به شبکه حمل.",
    pain: "ظرفیت مراکز لجستیک از جریان حمل جدا است.",
    solution: "iKIA مراکز لجستیک را به شبکه بار و ظرفیت وصل می‌کند.",
    status: "strategic-future",
    targetUsers: ["مراکز لجستیک", "انبارها"],
    route: "/solutions/logistics-hubs",
    icon: "hub",
    cta: "گفتگو درباره همکاری",
    category: "solution",
    detail: {
      pains: [
        { title: "ظرفیت جدا", desc: "انبار و حمل هماهنگ نیستند." },
        { title: "نبود تقاضا", desc: "اتصال به جریان بار محدود است." },
        { title: "عملیات دستی", desc: "هماهنگی ورود و خروج کند است." },
      ],
      capabilities: [
        { icon: "hub", title: "اتصال شبکه", desc: "اتصال مرکز به شبکه بار." },
        { icon: "warehouse", title: "مدیریت ظرفیت", desc: "عرضه ظرفیت انبار." },
        { icon: "order", title: "اتصال به سفارش", desc: "هماهنگی با جریان حمل." },
        { icon: "analytics", title: "گزارش بهره‌وری", desc: "شاخص‌های مرکز لجستیک." },
      ],
      steps: [
        { title: "اتصال", desc: "مرکز به شبکه iKIA وصل می‌شود." },
        { title: "عرضه ظرفیت", desc: "ظرفیت انبار اعلام می‌شود." },
        { title: "هماهنگی", desc: "بار و انبار هماهنگ می‌شوند." },
        { title: "بهره‌وری", desc: "گردش کالا افزایش می‌یابد." },
      ],
      controls: [
        { title: "سوابق ظرفیت", desc: "ثبت دقیق ورود و خروج." },
        { title: "دسترسی کنترل‌شده", desc: "مدیریت داده مرکز." },
        { title: "گزارش گردش", desc: "تحلیل بهره‌وری." },
      ],
    },
  },
  {
    key: "enterprise",
    faTitle: "سازمان‌ها",
    enTitle: "Enterprises / Traders",
    value: "حمل سازمانی، گزارش مدیریتی، کنترل چندکاربره و آمادگی API.",
    pain: "سازمان‌ها به دید مدیریتی و کنترل دسترسی نیاز دارند.",
    solution: "iKIA حمل سازمانی را با گزارش و کنترل یکپارچه می‌کند.",
    status: "near-future",
    targetUsers: ["سازمان‌ها", "بازرگانان بین‌الملل"],
    route: "/solutions/enterprise",
    icon: "enterprise",
    cta: "درخواست دمو",
    category: "solution",
    detail: {
      pains: [
        { title: "نبود دید کلان", desc: "گزارش یکپارچه وجود ندارد." },
        { title: "کنترل دسترسی", desc: "مدیریت چند کاربر سخت است." },
        { title: "یکپارچگی سامانه", desc: "اتصال به سامانه داخلی لازم است." },
      ],
      capabilities: [
        { icon: "enterprise", title: "حمل سازمانی", desc: "مدیریت حجم بالای بار." },
        { icon: "trending", title: "گزارش مدیریتی", desc: "نمای کلان عملکرد و هزینه." },
        { icon: "users", title: "کنترل چندکاربره", desc: "نقش و دسترسی کنترل‌شده." },
        { icon: "api", title: "آمادگی API", desc: "اتصال به سامانه‌های سازمان." },
      ],
      steps: [
        { title: "تماس", desc: "نیاز سازمان را مطرح کنید." },
        { title: "دمو", desc: "قابلیت‌ها را ببینید." },
        { title: "راه‌اندازی", desc: "کاربران و نقش‌ها را تنظیم کنید." },
        { title: "گزارش", desc: "عملکرد را دنبال کنید." },
      ],
      controls: [
        { title: "دسترسی نقش‌محور", desc: "کنترل دقیق دسترسی." },
        { title: "سوابق سازمانی", desc: "ممیزی فعالیت‌ها." },
        { title: "یکپارچگی امن", desc: "اتصال کنترل‌شده API." },
      ],
    },
  },
  {
    key: "government",
    faTitle: "نهادهای حاکمیتی",
    enTitle: "Government / Regulatory",
    value: "شفافیت، داده کریدوری و انطباق برای نهادهای حاکمیتی.",
    pain: "نهادها به داده شفاف کریدور و ترانزیت نیاز دارند.",
    solution: "iKIA داده عملیاتی کریدورها را شفاف و قابل اتکا می‌کند.",
    status: "strategic-future",
    targetUsers: ["نهادهای حاکمیتی", "گمرک"],
    route: "/solutions/government",
    icon: "government",
    cta: "گفتگو درباره همکاری",
    category: "solution",
    detail: {
      pains: [
        { title: "داده پراکنده", desc: "اطلاعات کریدور یکپارچه نیست." },
        { title: "نبود شفافیت", desc: "پایش ترانزیت دشوار است." },
        { title: "انطباق دستی", desc: "کنترل مقرراتی کند است." },
      ],
      capabilities: [
        { icon: "government", title: "داده کریدوری", desc: "نمای داده ترانزیت و کریدور." },
        { icon: "compliance", title: "انطباق", desc: "چارچوب رعایت مقررات." },
        { icon: "audit", title: "سوابق شفاف", desc: "ردگیری قابل ممیزی." },
        { icon: "analytics", title: "گزارش ملی", desc: "شاخص‌های کلان لجستیک." },
      ],
      steps: [
        { title: "تعریف نیاز", desc: "نیاز داده‌ای مشخص می‌شود." },
        { title: "اتصال", desc: "داده کریدور فراهم می‌شود." },
        { title: "پایش", desc: "ترانزیت شفاف دیده می‌شود." },
        { title: "گزارش", desc: "بینش کلان ارائه می‌شود." },
      ],
      controls: [
        { title: "حریم و امنیت", desc: "دسترسی کنترل‌شده به داده." },
        { title: "سوابق ممیزی", desc: "ثبت کامل برای حسابرسی." },
        { title: "شفافیت", desc: "داده قابل اتکا." },
      ],
    },
  },
];
