import type { ModuleEntry } from "./types";

export const VALUE_ADDED: ModuleEntry[] = [
  {
    key: "warehousing",
    faTitle: "انبارداری دیجیتال",
    enTitle: "Digital Warehousing / WMS / Fulfillment",
    value: "انبار، سامانه مدیریت انبار و تکمیل سفارش به‌صورت سرویس.",
    pain: "ظرفیت انبار و عملیات تکمیل سفارش از حمل جدا و ناهماهنگ است.",
    solution: "iKIA انبار، WMS و فولفیلمنت را به جریان حمل وصل می‌کند.",
    status: "strategic-future",
    targetUsers: ["صاحبان بار", "مراکز لجستیک"],
    route: "/value-added/warehousing",
    icon: "warehouse",
    cta: "گفتگو درباره انبارداری",
    category: "value-added",
    detail: {
      pains: [
        { title: "انبار جدا از حمل", desc: "موجودی و حمل هماهنگ نیستند." },
        { title: "عملیات دستی", desc: "ورود و خروج کالا کند و خطاپذیر است." },
        { title: "نبود دید موجودی", desc: "وضعیت موجودی شفاف نیست." },
      ],
      capabilities: [
        { icon: "warehouse", title: "مدیریت انبار", desc: "ورود، خروج و موجودی دیجیتال." },
        { icon: "fulfillment", title: "تکمیل سفارش", desc: "آماده‌سازی و ارسال سفارش." },
        { icon: "order", title: "اتصال به حمل", desc: "هماهنگی انبار با سفارش حمل." },
        { icon: "analytics", title: "گزارش موجودی", desc: "شاخص‌های انبار و گردش کالا." },
      ],
      steps: [
        { title: "دریافت", desc: "کالا در انبار ثبت می‌شود." },
        { title: "نگه‌داری", desc: "موجودی به‌صورت دیجیتال مدیریت می‌شود." },
        { title: "تکمیل", desc: "سفارش آماده و ارسال می‌شود." },
        { title: "حمل", desc: "اتصال مستقیم به حمل iKIA." },
      ],
      controls: [
        { title: "ردیابی موجودی", desc: "سوابق دقیق کالا." },
        { title: "دسترسی نقش‌محور", desc: "کنترل مشاهده موجودی." },
        { title: "گزارش گردش", desc: "تحلیل ورود و خروج." },
      ],
    },
  },
  {
    key: "insurance",
    faTitle: "بیمه حمل",
    enTitle: "Cargo Insurance",
    value: "پوشش بیمه‌ای یکپارچه برای محموله در طول مسیر.",
    pain: "تهیه بیمه جدا از حمل، کند و پراکنده است.",
    solution: "iKIA بیمه را به جریان حمل و اسناد متصل می‌کند.",
    status: "strategic-future",
    targetUsers: ["صاحبان بار", "فورواردرها"],
    route: "/value-added/insurance",
    icon: "insurance",
    cta: "گفتگو درباره بیمه",
    category: "value-added",
    detail: {
      pains: [
        { title: "فرایند جدا", desc: "بیمه خارج از پلتفرم حمل تهیه می‌شود." },
        { title: "ابهام پوشش", desc: "شرایط پوشش روشن نیست." },
        { title: "خسارت کند", desc: "پیگیری خسارت زمان‌بر است." },
      ],
      capabilities: [
        { icon: "insurance", title: "پوشش یکپارچه", desc: "بیمه متصل به محموله." },
        { icon: "documents", title: "اسناد بیمه", desc: "مدارک بیمه در کنار اسناد حمل." },
        { icon: "tracking", title: "پایش ریسک", desc: "ارتباط بیمه با وضعیت سفر." },
        { icon: "finance", title: "تسویه خسارت", desc: "آماده‌سازی فرایند خسارت." },
      ],
      steps: [
        { title: "انتخاب پوشش", desc: "پوشش مناسب بار انتخاب می‌شود." },
        { title: "صدور", desc: "بیمه به محموله متصل می‌شود." },
        { title: "پایش", desc: "ریسک در طول سفر دیده می‌شود." },
        { title: "تسویه", desc: "در صورت خسارت، فرایند آغاز می‌شود." },
      ],
      controls: [
        { title: "سوابق پوشش", desc: "ثبت کامل شرایط بیمه." },
        { title: "شفافیت شرایط", desc: "نمایش روشن پوشش." },
        { title: "آماده ممیزی", desc: "مدارک قابل حسابرسی." },
      ],
    },
  },
  {
    key: "finance",
    faTitle: "تسویه و تأمین مالی",
    enTitle: "Settlement & Supply-Chain Finance",
    value: "آمادگی تسویه، کنترل مالی و تأمین مالی زنجیره تأمین.",
    pain: "تسویه و جریان نقدی در لجستیک کند و مبهم است.",
    solution: "iKIA زیرساخت شفافیت و آمادگی تسویه مالی را فراهم می‌کند.",
    status: "near-future",
    targetUsers: ["صاحبان بار", "فورواردرها", "کریرها"],
    route: "/value-added/finance",
    icon: "finance",
    cta: "گفتگو درباره تسویه",
    category: "value-added",
    detail: {
      pains: [
        { title: "تسویه کند", desc: "جریان نقدی دیر و مبهم است." },
        { title: "نبود شفافیت", desc: "وضعیت مالی هر محموله روشن نیست." },
        { title: "دسترسی محدود به نقدینگی", desc: "تأمین مالی زنجیره دشوار است." },
      ],
      capabilities: [
        { icon: "receipt", title: "شفافیت مالی", desc: "وضعیت مالی روشن هر محموله." },
        { icon: "settlement", title: "آمادگی تسویه", desc: "زیرساخت آماده برای تسویه." },
        { icon: "finance", title: "تأمین مالی زنجیره", desc: "مسیر دسترسی به نقدینگی." },
        { icon: "audit", title: "سوابق مالی", desc: "ثبت قابل ممیزی." },
      ],
      steps: [
        { title: "ثبت مالی", desc: "مبالغ و وضعیت ثبت می‌شوند." },
        { title: "کنترل", desc: "دسترسی نقش‌محور به داده مالی." },
        { title: "آماده‌سازی تسویه", desc: "زمینه تسویه فراهم می‌شود." },
        { title: "گزارش", desc: "شاخص‌های مالی عملیات." },
      ],
      controls: [
        { title: "بدون پرداخت زنده", desc: "تمرکز بر آمادگی، نه درگاه فعال." },
        { title: "دسترسی کنترل‌شده", desc: "مشاهده مالی بر اساس نقش." },
        { title: "سوابق حسابرسی", desc: "آماده برای ممیزی." },
      ],
    },
  },
  {
    key: "customs",
    faTitle: "گمرک و ترخیص دیجیتال",
    enTitle: "Customs Brokerage",
    value: "ترخیص و امور گمرکی به‌صورت دیجیتال و یکپارچه با حمل.",
    pain: "امور گمرکی پیچیده، کاغذی و گلوگاه عملیات است.",
    solution: "iKIA اسناد گمرکی و ترخیص را به جریان حمل وصل می‌کند.",
    status: "strategic-future",
    targetUsers: ["بازرگانان", "فورواردرها"],
    route: "/value-added/customs",
    icon: "customs",
    cta: "گفتگو درباره گمرک",
    category: "value-added",
    detail: {
      pains: [
        { title: "فرایند کاغذی", desc: "اظهار و ترخیص دستی و کند است." },
        { title: "گلوگاه مرز", desc: "تأخیر گمرکی کل سفر را کند می‌کند." },
        { title: "ریسک انطباق", desc: "خطای مدارک پرهزینه است." },
      ],
      capabilities: [
        { icon: "customs", title: "اظهار دیجیتال", desc: "آماده‌سازی اظهارنامه و مدارک." },
        { icon: "documents", title: "اسناد گمرکی", desc: "مدارک ترخیص یکپارچه." },
        { icon: "compliance", title: "کنترل تطبیق", desc: "رعایت الزامات گمرکی." },
        { icon: "corridor", title: "هماهنگی مرز", desc: "مدیریت گذرگاه‌های مرزی." },
      ],
      steps: [
        { title: "آماده‌سازی", desc: "مدارک گمرکی تهیه می‌شوند." },
        { title: "اظهار", desc: "اظهارنامه ثبت و تطبیق می‌شود." },
        { title: "ترخیص", desc: "کالا از گمرک ترخیص می‌شود." },
        { title: "ادامه حمل", desc: "اتصال مستقیم به سفر حمل." },
      ],
      controls: [
        { title: "سوابق گمرکی", desc: "ثبت کامل برای انطباق." },
        { title: "کنترل اسناد", desc: "تطبیق پیش از مرز." },
        { title: "آماده ممیزی", desc: "مدارک قابل حسابرسی." },
      ],
    },
  },
  {
    key: "data-ai",
    faTitle: "داده و هوش مصنوعی",
    enTitle: "Data & AI Insights",
    value: "بینش پیش‌بینانه و بهینه‌سازی عملیات با داده و هوش مصنوعی.",
    pain: "داده عملیات استفاده نمی‌شود و تصمیم‌ها شهودی‌اند.",
    solution: "iKIA داده عملیات را به بینش و پیش‌بینی تبدیل می‌کند.",
    status: "strategic-future",
    targetUsers: ["مدیران", "سازمان‌ها"],
    route: "/value-added/data-ai",
    icon: "dataai",
    cta: "گفتگو درباره داده و AI",
    category: "value-added",
    detail: {
      pains: [
        { title: "داده بلااستفاده", desc: "داده عملیات تحلیل نمی‌شود." },
        { title: "تصمیم شهودی", desc: "تصمیم‌ها بدون پشتوانه داده‌اند." },
        { title: "نبود پیش‌بینی", desc: "تأخیر و ریسک پیش‌بینی نمی‌شود." },
      ],
      capabilities: [
        { icon: "dataai", title: "بینش پیش‌بینانه", desc: "پیش‌بینی تأخیر و ریسک." },
        { icon: "analytics", title: "تحلیل عملکرد", desc: "شاخص‌های کلیدی عملیات." },
        { icon: "route", title: "بهینه‌سازی مسیر", desc: "پیشنهاد مسیر بهینه." },
        { icon: "insight", title: "کشف الگو", desc: "شناسایی فرصت بهبود." },
      ],
      steps: [
        { title: "جمع‌آوری", desc: "داده عملیات گردآوری می‌شود." },
        { title: "تحلیل", desc: "الگوها و شاخص‌ها استخراج می‌شوند." },
        { title: "پیش‌بینی", desc: "ریسک و تأخیر پیش‌بینی می‌شود." },
        { title: "اقدام", desc: "بینش به تصمیم تبدیل می‌شود." },
      ],
      controls: [
        { title: "حریم داده", desc: "حفاظت و دسترسی کنترل‌شده." },
        { title: "شفافیت مدل", desc: "بینش قابل تفسیر." },
        { title: "بهبود مستمر", desc: "به‌روزرسانی با داده جدید." },
      ],
    },
  },
];
